version: '3'
services:
  node-app:
    image: kooroushpsnd/mevn
    env_file:
      - ./.env
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    
  mongo:
    image: mongo:4.4
    volumes:
      - mongo-db:/data/db

  vue-js:
    image: kooroushpsnd/mevn.front
    ports:
      - "8080:8080"
    
volumes:
  mongo-db: