version: '3'
services:
  node-app:
    build: .
    image: node
    env_file:
      - ./.env.production
    depends_on:
      - mongo
    
  mongo:
    image: mongo:4.4
    volumes:
      - mongo-db:data/db
    
volumes:
  mongo-db: